Update check-container.rb
I got this to problems:

WARNING: Error: #<NameError: undefined local variable or method `container_state' for #<CheckDockerContainer:0x0000000202c428>

container_state had no prior declaration.

response.code.to_i == 404 If the container does not exist, we'll always get 404.